################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
components/nwk\ applications/nwk_freq.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_freq.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_freq.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/nwk\ applications/nwk_ioctl.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_ioctl.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_ioctl.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/nwk\ applications/nwk_join.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_join.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_join.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/nwk\ applications/nwk_link.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_link.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_link.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/nwk\ applications/nwk_mgmt.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_mgmt.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_mgmt.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/nwk\ applications/nwk_ping.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_ping.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_ping.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '

components/nwk\ applications/nwk_security.obj: C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications/nwk_security.c $(GEN_OPTS) $(GEN_HDRS)
	@echo 'Building file: $<'
	@echo 'Invoking: MSP430 Compiler'
	"C:/ti/ccsv5/tools/compiler/msp430_4.2.1/bin/cl430" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\smpl_nwk_config.dat" --cmd_file="C:\Users\jmanton\work\msp430-2\trunk\CCS\CCS application\SimpliciTI test\application\configuration\End_Device\smpl_config.dat"  -vmsp --abi=eabi -g --include_path="C:/ti/ccsv5/ccs_base/msp430/include" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp/drivers" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/bsp" --include_path="C:/Users/jmanton/work/msp430-2/trunk/CCS/LP_AIR_CC110L_G2553" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/mrfi" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk" --include_path="C:/Users/jmanton/work/SimpliciTI-CCS-1.1.1/Components/simpliciti/nwk_applications" --include_path="C:/ti/ccsv5/tools/compiler/msp430_4.2.1/include" --advice:power=all --define=__MSP430G2553__ --define=FREQUENCY_AGILITY --define=MRFI_CC1101 --diag_warning=225 --display_error_number --diag_wrap=off --printf_support=minimal --preproc_with_compile --preproc_dependency="components/nwk applications/nwk_security.pp" --obj_directory="components/nwk applications" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: $<'
	@echo ' '


